### ISSUE TITLE
Expose read only property in the playground-file-editor

### ISSUE THREAD

**Issue by GeorgePlukov** [PolymerLabs/playground-elements#150]
My goal is to use this package to create both an interactive demo experience for our component library (built using lit) and to provide inline (non-editable) demo snippets that users can quickly copy paste. 

I noticed the playground-code-editor component has a readonly property that is set but it would be nice if the file editor exposed an override to make it always non-editable. If possible maybe hiding the cursor in readonly mode. 

Side-note: Is there instructions for contributing to the project and getting it set up locally? I attempted to pull and run the code but wasn't successful getting it running

**Comment by aomarks** [comment]
Sure, adding a `readonly` property to `file-editor` makes sense.

If you're interested in contributing, that should be a pretty straightforward feature to add!

I've just sent out https://github.com/PolymerLabs/playground-elements/pull/151 with a quick setup guide for contributors. Here it is rendered: https://github.com/PolymerLabs/playground-elements/blob/c25598bb1f474b6c06640efa2d9f43d0380fb611/README.md#contributing

**Comment by GeorgePlukov** [comment]
Awesome! Thanks for adding the contributing section. I'm more than happy to add that in myself

**Comment by aomarks** [comment]
Published in v0.9.4
