### ISSUE TITLE
When running playground-elements/configurator locally playground-preview is unable to resolve files

### ISSUE THREAD

**Issue by GeorgePlukov** [PolymerLabs/playground-elements#156]
When I first began using the playground elements the previews would resolve properly but at some point since then (I don't believe changes were made) the files began failing to resolve and the preview is stuck in a pending state for a long time. 

This is occurring using the default playground configurator setup and with some custom layout arrangements I was experimenting with. 

Have you encountered this before? I'm unsure what is causing it as I believe that those files should be served from the service worker.  Is it possible that there is rate limiting happening on the unpkg?

<img width="698" alt="Screen Shot 2021-05-18 at 8 07 08 AM" src="https://user-images.githubusercontent.com/1743751/118648386-54d05a80-b7b0-11eb-8b02-b1f65a2ae8b4.png">

**Comment by aomarks** [comment]
Hmm, yeah it looks like the service worker is not handling those requests for some reason, since that's the unpkg.com 404 response. Will see if I can reproduce.

If you open it in an incognito window, does it start working again?

**Comment by GeorgePlukov** [comment]
The incognito window seems to behave similarly except there is an additional error in console.

`  VM5 playground-service-worker-proxy.html:11 Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://unpkg.com/playground-elements@0.9.3/playground-projects/') with script ('https://unpkg.com/playground-elements@0.9.3/playground-service-worker.js'): The user denied permission to use Service Worker.
  (anonymous) @ VM5 playground-service-worker-proxy.html:11
  async function (async)
  (anonymous) @ VM5 playground-service-worker-proxy.html:11
  (anonymous) @ VM5 playground-service-worker-proxy.html:11`

**Comment by aomarks** [comment]
I've just released v0.9.4 with https://github.com/PolymerLabs/playground-elements/pull/158 that I'm optimistic will fix this issue. Could you upgrade and confirm?

**Comment by GeorgePlukov** [comment]
Fixed for me now! Thanks for getting to this so quickly

**Comment by jmarcosfer** [comment]
Just FYI, I was also getting this same error when using version 0.20.0 of the library, which is the one that npm installs by default. It seemed to go away when I downgraded to the latest (I presume stable) version that appears here on the github repo, version 0.18.1
