### ISSUE TITLE
Configurator/demo not load. 

### ISSUE THREAD

**Issue by ggsalas** [PolymerLabs/playground-elements#157]
I have followed the [steps to run the configurator/demo](https://github.com/PolymerLabs/playground-elements/blob/5eb394641a3aac05f4c27767fd7b51affa297044/README.md#contributing) locally, and I get only a loading state. Seems a CORS issue.

I'm trying this because the same issue is affecting my app where I use playground-elements.

https://user-images.githubusercontent.com/8403993/118699479-f7580000-b7e7-11eb-81ff-7c137839fb5d.mov

![image](https://user-images.githubusercontent.com/8403993/118699452-ef985b80-b7e7-11eb-8e0c-8ca916b22520.png)

**Comment by aomarks** [comment]
I've just released v0.9.4 with https://github.com/PolymerLabs/playground-elements/pull/158 that I'm optimistic will fix this issue. Could you upgrade and confirm?

**Comment by aomarks** [comment]
Marking this fixed, but please re-open if it is still an issue.
