### ISSUE TITLE
Support incremental TypeScript compilation

### ISSUE THREAD

**Issue by aomarks** [PolymerLabs/playground-elements#185]
We currently do a completely fresh TypeScript compile on every change. It would be much more efficient to use TypeScript's support for incremental compilation.

**Comment by Matsuuu** [comment]
This would be resolved through https://github.com/PolymerLabs/playground-elements/pull/205 , right? Or is there still more work on this needed?

**Comment by aomarks** [comment]
This issue was kind of vague. I'll reword this one to refer to incremental compilation specifically and close it.

I've opened some more specific ones for the other kinds of caching I was thinking about.

https://github.com/PolymerLabs/playground-elements/issues/206
https://github.com/PolymerLabs/playground-elements/issues/207
https://github.com/PolymerLabs/playground-elements/issues/208
