### ISSUE TITLE
reload icon color not changing with foreground

### ISSUE THREAD

**Issue by e111077** [PolymerLabs/playground-elements#62]
setting `--playground-preview-toolbar-foreground-color` does not seem to change the color of the reload `icon-button` causing issues with dark mode. `mwc-icon-button`'s internals simply use `currentcolor` so just seems that you need to apply that foreground-color to that as well

**Comment by aomarks** [comment]
Released in https://github.com/PolymerLabs/playground-elements/releases/tag/v0.1.1
