### ISSUE TITLE
Give workers more descriptive names for bundling

### ISSUE THREAD

**Issue by e111077** [PolymerLabs/playground-elements#64]
Heya, currently trying to bundle for production and the workers are proving to be not fun. Currently the worker imports [here](https://github.com/PolymerLabs/playground-elements/blob/e9b091f90b7a75f3347b1b08544c2d5f24d4e613/src/playground-project.ts#L58) are using the names `service-worker.js` and `typescript-worker.js`. The first is a bit too generic of a name to rebundle that worker in a generic build output

**Comment by aomarks** [comment]
Released in 0.3.1
