### ISSUE TITLE
[suggestion] Consider VSCode as online code editor

### ISSUE THREAD

**Issue by daKmoR** [PolymerLabs/playground-elements#75]
I quite like working in vscode as it helps with the little things.

for example if I do 
1. If I hit "pos1" or "command + left" it goes to the first character in the line (not to the start of the line)
2. Or using Command + D to select the same word multiple times and then replacing it in one go
3. ...

As you can run vscode in the browser it could be a nice improvement for the writing experience.

Here I have a side by side comparison doing the same things (left playground-elements; right webcomponents.dev)

![vscodeeditor](https://user-images.githubusercontent.com/24378/97538957-86730700-19c1-11eb-8072-50e1080c0647.gif)

PS: just a suggestion - feel free to ignore - no hard feelings 🤗

**Comment by aomarks** [comment]
Hey @daKmoR! Yeah, agree that Monaco/VSCode is probably the best library out there in terms of features.

The driving use case we're working towards for this component is interactive code samples (e.g. on the lit-element website), and so load time/code size is a really important factor. I investigated Monaco recently (https://github.com/PolymerLabs/playground-elements/pull/53), and the build I got was 5X the size of CodeMirror 5 (and that's with no plugins, so no HTML-in-JS highlighting support). So the tradeoff didn't seem worth it, at least for our use case.

| Lib          | Raw    | Raw Gzip | Minified  | Minified Gzip |
|--------------|--------|----------|--------------|---------------|
| CodeMirror 5 | 539 kB | 141 kB   | 251 kB       | 77.4 kB       |
| CodeMirror 6 | 767 kB | 204 kB   | 344 kB       | 119 kB        |
| Monaco       | 4.2 MB | 725 kB   | 1.6 MB       | 405 kB        |

There are a bunch of extra features/addons for CodeMirror we should probably enable that I haven't looked into yet, including keyboard bindings, that would improve usability: https://codemirror.net/

We could also support swapping out the text editor component, where maybe we have a few options like `<playground-codemirror>` and `<playground-monaco>` (and `<playground-textarea>` for a super minimal case?). Maybe you'd slot your choice in, or just assemble all the pieces yourself.

This is (roughly) the current factoring of the elements, where `<playground-code-editor>` is where CodeMirror lives. So, any component that takes a `value` property and emits `change` could just drop in its place.

![image](https://user-images.githubusercontent.com/48894/97603080-4e6fc200-19c9-11eb-8939-d6f435becb72.png)

**Comment by daKmoR** [comment]
thank you for this detailed explanation 🤗

totally makes sense 👍
